<?php
namespace Modules\Tour\Models;

use App\BaseModel;
use Illuminate\Http\Request;

class TourMeta extends BaseModel
{
    protected $table    = 'bravo_tour_meta';
    protected $fillable = [
        'enable_person_types',
        'person_types',
        'enable_extra_price',
        'extra_price',
        'enable_open_hours',
        'open_hours',
        'discount_by_people',
        'ea_enable_person_types',
        'ea_person_types',
        'ea_enable_extra_price',
        'ea_extra_price',
        'ea_discount_by_people',
        'tz_enable_person_types',
        'tz_person_types',
        'tz_enable_extra_price',
        'tz_extra_price',
        'tz_discount_by_people',
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'person_types'       => 'array',
        'extra_price'        => 'array',
        'open_hours'         => 'array',
        'discount_by_people' => 'array',
        'ea_person_types'       => 'array',
        'ea_extra_price'        => 'array',
        'ea_discount_by_people' => 'array',
        'tz_person_types'       => 'array',
        'tz_extra_price'        => 'array',
        'tz_discount_by_people' => 'array',
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ( $this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
